### ISSUE TITLE
Tamaño Elipse

### ISSUE THREAD

**Issue by Hernan4444** [IIC2433-2017-2/T03#3]
En clases se dijo que debe poder observarse las elipses de las gaussianas en los gráficos, pero no recuerdo hasta que porcentaje de probabilidad, ¿90, 95, 100?

Gracias de antemano
Saludos ✌️

**Comment by bcsaldias** [comment]
Eso es un detalle, puedes pasarlo cómo parametro?

Cómo sería con 100%? .. eso abarca todo el dominio verdad?

Recomiendo dejarlo con 95% o 97.5%.

Saludos!
