### ISSUE TITLE
Path Base de datos

### ISSUE THREAD

**Issue by Hernan4444** [IIC2433-2017-2/T03#4]
Hola (de nuevo),

En el enunciado se dice:
> EMGM.ipynb: Este archivo, lee una base de datos, la preprocesa y corre el algoritmo EMGM sobre ella. Además, crea un archivo de output donde entrega cada dato con su probabilidad de pertenencia a cada Gaussiana. Se deben poder configurar los siguientes parámetros: el path a la base de datos, el número de Gaussianas que se quieren ajustar, si se quiere una versión iterativa o no.

Con respecto al __path a la base de datos__, se refiere a la base de datos de entrada o a la base de datos de salida?

Si es el de entrada, podemos definir que el path debe ser el de una base de datos creada por `GeneracionDatos.ipynb`?

Gracias de antemano
Saludos ✌️

**Comment by bcsaldias** [comment]
Si, entrada. Por defecto si, por supuesto.

Saludos!
